#!/bin/bash

NAME=cpio-unpack
VERSION=0.1.0

function help()
{
    echo -e "\`$NAME' unpacks cpio archives\n"                   \
	    "\n"                                                 \
	    "Usage: $NAME -f CPIO -d DIR\n"                      \
	    " -?, --help      Show this help statement\n"        \
	    "     --version   Show version statement\n"          \
	    " -f, --file CPIO Use CPIO as input archive\n"       \
	    " -d, --dir DIR   Create output in directory DIR\n"  \
	    "\n"                                                 \
	    "Examples: $NAME -f foo.cpio -d foo\n";
}

function work()
{
    local cpio=$1;
    local dir=$2;

    cpio=$(cd $(dirname $cpio) && pwd)/$(basename $cpio);

    mkdir $dir &&
    cd $dir &&
    test -f $cpio &&
    sudo cpio -id --quiet --no-absolute-filenames < $cpio ||
    return 1;

    return 0;
}

function main()
{
    local dir; 
    local cpio;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            echo "$NAME $VERSION"; return 1;
            ;;
        -f | --file)
            shift; cpio=$1; shift;
            ;;
        -d | --dir)
            shift; dir=$1; shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done
   
    [ -f "$cpio" -a -n "$dir" ] || { 
    	help;
	return 1;
    }

    [ -d "$dir" ] && {
    	echo "$NAME: refusing to clobber directory: $dir"; 
	return 1;
    }

    work $cpio $dir || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
