#!/bin/bash

NAME=cpio-unpack

function help()
{
    echo -e "\`$NAME' unpacks cpio archives\n"                   \
	    "\n"                                                 \
	    "Usage: $NAME -f CPIO -d DIR\n"                      \
	    " -?, --help      Show this help statement\n"        \
	    "     --version   Show version statement\n"          \
	    " -f, --file CPIO Use CPIO as input archive\n"       \
	    " -d, --dir DIR   Create output in directory DIR\n"  \
	    "\n"                                                 \
	    "Examples: $NAME -f foo.cpio -d foo\n";
}

function work()
{
    local cpio=$1;
    local dir=$2;
    local cat=cat; 

    file $cpio | grep -q "gzip compressed data" && {
        cat=zcat;
    }

    test -f $cpio &&
    mkdir -p $dir &&
    cd $dir &&
    $cat $cpio | sudo cpio -id -u --quiet --no-absolute-filenames ||
    return 1;

    return 0;
}

function main()
{
    local dir; 
    local cpio;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            nbic --version; return 1;
            ;;
        -f | --file)
            shift;
            cpio=$(cd $(dirname $1) && pwd)/$(basename $1);
            shift;
            ;;
        -d | --dir)
            shift;
            dir=$(cd $(dirname $1) && pwd)/$(basename $1);
            shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done
   
    [ -f "$cpio" -a -n "$dir" ] || { 
    	help;
	return 1;
    }

    work $cpio $dir || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
