#!/bin/bash

NAME=cpio-edit
VERSION=0.2.0

function help()
{
    echo -e "\`$NAME' edits cpio archives by allowing user to chroot\n"  \
	    "\n"                                                         \
	    "Usage: $NAME -f CPIO\n"                                     \
	    " -?, --help      Show this help statement\n"                \
	    "     --version   Show version statement\n"                  \
	    " -f, --file CPIO Use CPIO as input archive\n"               \
	    "\n"                                                         \
	    "Examples: $NAME -f foo.cpio\n";
}

function work()
{
    local cpio=$1;

    local dir=$(mktemp -d $cpio.XXXXXX);
    local tmp=$cpio.edit;

    cpio-unpack -f $cpio -d $dir &&
    sudo chroot $dir /chroot &&
    cpio-pack -d $dir -o $tmp &&
    sudo rm -r -f $dir &&
    mv $tmp $cpio ||
    return 1;

    return 0;
}

function main()
{
    local dir; 
    local cpio;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            echo "$NAME $VERSION"; return 1;
            ;;
        -f | --file)
            shift; cpio=$1; shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done
   
    [ -f "$cpio" ] || { 
    	help;
	return 1;
    }

    work $cpio || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
