#!/bin/bash

NAME=cpio-pack

function help()
{
    echo -e "\`$NAME' packs cpio archives\n"                     \
	    "\n"                                                 \
	    "Usage: $NAME -d DIR -o CPIO\n"                      \
	    " -?, --help      Show this help statement\n"        \
	    "     --version   Show version statement\n"          \
	    " -d, --dir DIR   Use directory DIR as input\n"      \
	    " -o, --out CPIO  Create output archive CPIO\n"      \
	    "\n"                                                 \
	    "Examples: $NAME -d foo -o foo.cpio\n";
}

function work()
{
    local dir=$1;
    local cpio=$2;

    local list=$(mktemp);

    cpio=$(cd $(dirname $cpio) && pwd)/$(basename $cpio);

    cd $dir &&
    sudo find . > $list &&
    cd $OLDPWD &&
    rm -f $cpio &&
    nbic -d $dir -l $list -o $cpio ||
    return 1;

    return 0;
}

function main()
{
    local dir; 
    local cpio;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            nbic --version; return 1;
            ;;
        -d | --dir)
            shift; dir=$1; shift;
            ;;
        -o | --out)
            shift; cpio=$1; shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done
   
    [ -d "$dir" -a -n "$cpio" ] || { 
    	help;
	return 1;
    }

    work $dir $cpio || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
