#!/bin/bash

NAME=cpio-add

function help()
{
    echo -e "\`$NAME' adds files to an existing cpio archive\n"    \
	    "\n"                                                   \
	    "Usage: $NAME CPIO FILE1 [FILE2 ...]\n"                \
	    " -?, --help      Show this help statement.\n"         \
	    "     --version   Show version statement.\n"           \
	    "\n"                                                   \
	    "Examples: $NAME cpio-add ../iptables.cpio init\n";
}

function work()
{
    local cpio=$1;
    local files="$2";

    /bin/ls $files | sudo cpio -o -A -H newc --quiet -F $cpio || return 1;

    return 0;
}

function main()
{
    local cpio;
    local files;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            nbic --version; return 1;
            ;;
        *)
            if [ -z "$cpio" ]; then
	    	cpio=$1;
	    else
	    	files="$files $1";
	    fi
	    shift;
            ;;
        esac
    done

    [ -z "$cpio" -o -z "$files" ] && { 
    	help; 
	return 1;
    }

    work $cpio "$files" || { 
    	echo "$NAME: bailing out because of errors"; return 1;
    }

    return 0;
}

main "$@";
exit $?;
