#!/bin/bash

NAME=cpio-edit
VERSION=0.2.1

function help()
{
    echo -e "\`$NAME' edits cpio archives by dropping user in chroot shell\n" \
	    "\n"                                                              \
	    "Usage: $NAME CPIO\n"                                             \
	    " -?, --help      Show this help statement\n"                     \
	    "     --version   Show version statement\n"                       \
	    "\n"                                                              \
	    "Examples: $NAME foo.cpio\n";
}

function work()
{
    local cpio=$1;

    local dir=$(mktemp -d $cpio.XXXXXX);
    local tmp=$(mktemp $cpio.XXXXXX);

    cpio-unpack -f $cpio -d $dir &&
    nd $dir &&
    cpio-pack -d $dir -o $tmp &&
    sudo rm -r -f $dir &&
    sudo mv -f $tmp $cpio &&
    sudo chown $USER $cpio ||
    return 1;

    return 0;
}

function main()
{
    local cpio;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            echo "$NAME $VERSION"; return 1;
            ;;
        *)
            cpio=$1;
	    shift;
            ;;
        esac
    done
   
    [ -f "$cpio" ] || { 
    	help;
	return 1;
    }

    work $cpio || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
