#!/bin/bash

NAME=cpio-fsck

function help()
{
    echo -e "\`$NAME' checks a cpio against its reference directory\n" \
	    "\n"                                                       \
	    "Usage: $NAME CPIO DIR\n"                                  \
	    " -?, --help      Show this help statement\n"              \
	    "     --version   Show version statement\n"                \
	    "\n"                                                       \
	    "Examples: $NAME foo.cpio foo\n";
}

function work()
{
    local cpio=$1;
    local dir=$2;
    local tmp=$(mktemp -d dir.XXXXXX)
    local bad=$(mktemp bad.XXXXXX)
    local good=$(mktemp good.XXXXXX)
    local sums=$(mktemp sums.XXXXXX)

    cpio-unpack -f $cpio -d $tmp ||
    return 1;

    cd $tmp &&
    sudo find * -type f > $OLDPWD/$bad &&
    xargs sudo md5sum < $OLDPWD/$bad > $OLDPWD/$sums &&
    cd $OLDPWD &&
    sudo rm -r -f $tmp &&
    rm $bad $good &&
    cd $dir &&    
    sudo md5sum -c $OLDPWD/$sums

    r=$?

    cd $OLDPWD &&
    rm $sums 

    return $r;
}

function main()
{
    local cpio;
    local dir;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            nbic --version; return 1;
            ;;
        *)
            if [ -z "$cpio" ]; then
	    	cpio=$1;
            elif [ -z "$dir" ]; then
	    	dir=$1;
	    else
	        echo "$NAME: too many arguments: $1";
		return 1;
	    fi
	    shift;
            ;;
        esac
    done
   
    [ -f "$cpio" -a -d "$dir" ] || {
    	help;
	return 1;
    }

    work "$cpio" "$dir" || { 
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
