#!/bin/bash

set -e

cpio=$1
name=${cpio%%.cpio}

test -z "$1" && {
    echo "usage: $(basename $0) CPIO"
    return 1
}

cp template.img $name.img
disk-cpio $cpio $name.img
qemu-img convert $name.img -O vmdk appliance.vmdk
rm -f $name.zip
rm -f -r $name
mkdir $name
cp appliance.vmx $name
mv appliance.vmdk $name
zip -9 -r $name.zip $name
rm -f -r $name
