#!/bin/bash

NAME=nbic
VERSION=0.1.0

function help()
{
    echo -e "\`$NAME' compiles cpio archives for netboot images\n" \
	    "\n"                                                   \
	    "Usage: $NAME -d DIR -i LIST -o CPIO\n"                \
	    " -?, --help       Show this help statement.\n"        \
	    "     --version    Show version statement.\n"          \
	    " -d, --dir DIR    Use DIR as input directory.\n"      \
	    " -i, --input LIST Use LIST as list of files.\n"       \
	    " -o, --out CPIO   Create output archive CPIO.\n"      \
	    "\n"                                                   \
	    "Examples: $NAME -d linux -i foo.list -o ramfs.cpio\n";
}

function work()
{
    local dir=$1;
    local out=$2;
    local list=$3;

    local raw;
    local cpio;
    local trim;

    out=$(cd $(dirname $out) && pwd)/$(basename $out);
    trim=$out.$$.d
    cpio=$out.$$.cpio
    final=/tmp/nbic.final.$$;
    raw=/tmp/nbic.raw.$$;

    cp $list $raw &&
    cd $dir &&
    echo "dev/console" >> $raw &&
    echo "dev/ptmx" >> $raw &&
    echo "dev/null" >> $raw &&
    echo "dev/pts" >> $raw &&
    echo "mnt" >> $raw &&
    echo "proc" >> $raw &&
    echo "sys" >> $raw &&
    echo "init" >> $raw &&
    sort $raw | uniq > $final &&
    sudo cpio -o --quiet -H newc -O $cpio < $final &&
    mkdir $trim &&
    cd $trim &&
    sudo cpio -id --quiet --no-absolute-filenames < $cpio &&
    sudo find . > $final &&
    sudo cpio -o --quiet -H newc -O $out < $final &&
    sudo rm $cpio $final &&
    sudo rm -r -f $trim || 
    return 1;

    return 0;
}

function main()
{
    local dir; local out;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            echo "$NAME $VERSION"; return 1;
            ;;
        -d | --dir)
            shift; dir=$1; shift;
            ;;
        -i | --input)
            shift; raw=$1; shift;
            ;;
        -o | --out)
            shift; out=$1; shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done

    [ -z "$out" ] && out=$PWD/nbic.cpio;

    [ -d "$dir" -a -n "$out" -a -n "$raw" ] || { help; return 1; }

    work $dir $out $raw || { 
    	echo "$NAME: bailing out because of errors"; return 1;
    }

    return 0;
}

main "$@";
exit $?;
