#!/bin/bash

if [ $HOSTNAME = bgdfen1 ]; then
    PREFIX=/bgl/BlueLight/ppcfloor/blrts-gnu/bin
    LD=$PREFIX/powerpc-bgl-blrts-gnu-ld
elif [ $HOSTNAME = bg31 ]; then
    PREFIX=/gsa/watgsa/home/j/a/jappavoo/Work/bg/bgp/work/gnu-linux/bin
    LD=$PREFIX/powerpc-bgp-linux-ld
else
    PREFIX=/bgp/sys/floors/midplane_36lab/gnu-linux/bin
    LD=$PREFIX/powerpc-bgp-linux-ld
fi

set -e

[ $# -eq 1 ] || { echo "usage: $(basename $0) CPIO"; exit 1; }

cp $1 ramdisk.cpio

$LD -b binary -e 0 -o ramdisk.cpio.elf ramdisk.cpio

$LD -T ramdisk.lds -o ramdisk.elf

echo ?amdisk.elf : OK
