#!/bin/bash

NAME=trace-files

function help()
{
    echo -e "\`$NAME' traces files accessed during an NFS boot\n"     \
	    "\n"                                                      \
	    "Usage: $NAME -d DIR -o CPIO\n"                           \
	    " -?, --help        Show this help statement\n"           \
	    "     --version     Show version statement\n"             \
	    " -t, --stamp STAMP Use file STAMP as reference\n"        \
	    " -d, --dir DIR     Use directory DIR as input\n"         \
	    " -o, --out LIST    Create LIST file of accessed files\n" \
	    "\n"                                                      \
	    "Examples: $NAME -t TIMESTAMP -d linux -o linux.list\n";
}

function work()
{
    local stamp=$1;
    local dir=$2;
    local list=$3;

    cd $dir &&
    sudo find * -anewer $stamp > $list &&
    chown $USER $list ||
    return 1;

    return 0;
}

function main()
{
    local stamp;
    local dir; 
    local list;

    while [ $# -gt 0 ]; do
        case $1 in
        -\? | --help)
            help; return 1;
            ;;
        --version)
            nbic --version; return 1;
            ;;
        -t | --stamp)
            shift; 
            stamp=$(cd $(dirname $1) && pwd)/$(basename $1);
            shift;
            ;;
        -d | --dir)
            shift;
            dir=$(cd $(dirname $1) && pwd)/$(basename $1);
            shift;
            ;;
        -o | --out)
            shift;
            list=$(cd $(dirname $1) && pwd)/$(basename $1);
            shift;
            ;;
        *)
	    echo "$NAME: bad argument: $1"; return 1;
            ;;
        esac
    done
   
    [ -f "$stamp" -a -d "$dir" -a -n "$list" ] || { 
    	help;
	return 1;
    }

    work $stamp $dir $list || { 
    	echo "$NAME: bailing out because of errors";
	return 1;
    }

    return 0;
}

main "$@";
exit $?;
